name: Continuous integration
on:
  push:
    branches:
      - devel
      - stable
  pull_request:
    branches:
      - devel
      - stable
jobs:
  tests:
    strategy:
      matrix:
        os: [ macos-11 ] # list of os: https://github.com/actions/virtual-environments
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive --force
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ matrix.os }}-go-${{ hashFiles('**/go.sum') }}
      - run: make test
